on:
  push:
    branches:
      - main
    paths:
      - smoke-tests/fakebackend/**
      - dependencyManagement/**
      - gradle/**
      - .github/workflows/docker-build-smoke-tests-fake-backend.yml

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
      - name: Build and push docker image
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: :smoke-tests:fakebackend:jib
